version: '3'

volumes:
  cache:
    driver: local
  db-data:
    driver: local

services:
  app:
    image: vladossss/booktracker:latest
#    build:
#      context: .
    container_name: booktracker
    restart: always
    depends_on:
      - db
      - redis
#    env_file:
#      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRESUSERNAME}
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
      - POSTGRES_DB=${POSTGRESDATABASE}
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDISPASSWORD}
    volumes:
      - cache:/data