spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDISHOST}
      port: 6379
      password: ${REDISPASSWORD}
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRESDATABASE}?currentSchema=${POSTGRESSCHEMA}
    username: ${POSTGRESUSERNAME}
    password: ${POSTGRESPASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: booktracker
security:
  jwt:
    secret: ${JWTSECRET}
    access: 1
    refresh: 30
springdoc:
  override-with-generic-response: false